// Auth Types
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

// Department Types
export const FETCH_DEPARTMENTS_START = 'FETCH_DEPARTMENTS_START';
export const FETCH_DEPARTMENTS_SUCCESS = 'FETCH_DEPARTMENTS_SUCCESS';
export const FETCH_DEPARTMENTS_FAILURE = 'FETCH_DEPARTMENTS_FAILURE';

export const FETCH_DEPARTMENT_START = 'FETCH_DEPARTMENT_START';
export const FETCH_DEPARTMENT_SUCCESS = 'FETCH_DEPARTMENT_SUCCESS';
export const FETCH_DEPARTMENT_FAILURE = 'FETCH_DEPARTMENT_FAILURE';

export const ADD_DEPARTMENT_START = 'ADD_DEPARTMENT_START';
export const ADD_DEPARTMENT_SUCCESS = 'ADD_DEPARTMENT_SUCCESS';
export const ADD_DEPARTMENT_FAILURE = 'ADD_DEPARTMENT_FAILURE';

export const UPDATE_DEPARTMENT_START = 'UPDATE_DEPARTMENT_START';
export const UPDATE_DEPARTMENT_SUCCESS = 'UPDATE_DEPARTMENT_SUCCESS';
export const UPDATE_DEPARTMENT_FAILURE = 'UPDATE_DEPARTMENT_FAILURE';

export const DELETE_DEPARTMENT_START = 'DELETE_DEPARTMENT_START';
export const DELETE_DEPARTMENT_SUCCESS = 'DELETE_DEPARTMENT_SUCCESS';
export const DELETE_DEPARTMENT_FAILURE = 'DELETE_DEPARTMENT_FAILURE';
// Directia userului
export const FETCH_USER_DIRECTIE_START = 'FETCH_USER_DIRECTIE_START';
export const FETCH_USER_DIRECTIE_SUCCESS = 'FETCH_USER_DIRECTIE_SUCCESS';
export const FETCH_USER_DIRECTIE_FAILURE = 'FETCH_USER_DIRECTIE_FAILURE';
// Partner Types
export const FETCH_PARTNERS_START = 'FETCH_PARTNERS_START';
export const FETCH_PARTNERS_SUCCESS = 'FETCH_PARTNERS_SUCCESS';
export const FETCH_PARTNERS_FAILURE = 'FETCH_PARTNERS_FAILURE';

export const FETCH_PARTNER_START = 'FETCH_PARTNER_START';
export const FETCH_PARTNER_SUCCESS = 'FETCH_PARTNER_SUCCESS';
export const FETCH_PARTNER_FAILURE = 'FETCH_PARTNER_FAILURE';

export const ADD_PARTNER_START = 'ADD_PARTNER_START';
export const ADD_PARTNER_SUCCESS = 'ADD_PARTNER_SUCCESS';
export const ADD_PARTNER_FAILURE = 'ADD_PARTNER_FAILURE';

export const UPDATE_PARTNER_START = 'UPDATE_PARTNER_START';
export const UPDATE_PARTNER_SUCCESS = 'UPDATE_PARTNER_SUCCESS';
export const UPDATE_PARTNER_FAILURE = 'UPDATE_PARTNER_FAILURE';

export const DELETE_PARTNER_START = 'DELETE_PARTNER_START';
export const DELETE_PARTNER_SUCCESS = 'DELETE_PARTNER_SUCCESS';
export const DELETE_PARTNER_FAILURE = 'DELETE_PARTNER_FAILURE';
